home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('faq/', views.faq, name='faq'),
]

meu_aroma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from .views import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('shopping_bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'meu_aroma.views.handler404'

products/urls.py
from django.urls import path
from . import views
from .views import update_inventory

urlpatterns = [
    path('', views.all_products, name='products'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('product/<int:product_id>/update_inventory/', update_inventory, name='update_inventory'),
    path('product/<int:product_id>/feedback/', views.product_feedback, name='product_feedback'),
]

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Inventory, Feedback

class QuantityForm(forms.Form):
    """
    Form for specifying the quantity of a product.

    Fields:
        quantity (IntegerField): The quantity of the product.
        
    """
    quantity = forms.IntegerField(min_value=1,
                                  max_value=99,
                                  label='Quantity')


    image = forms.ImageField(label='Image',
                             required=False,
                             widget=CustomClearableFileInput)    

class ProductForm(forms.ModelForm):
    """
    Form for creating or editing a product.

    Meta:
        model (Product): The Product model
        associated with the form.
        fields (list): The fields to include
        in the form.
        widgets (dict): Custom widgets for form fields.
        
    Methods:
        __init__(): Initializes the form and sets
        custom attributes for form fields.

    """
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'image': CustomClearableFileInput(attrs={'class': 
                'form-control custom-class another-class'}),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control custom-class another-class'
            
class InventoryForm(forms.ModelForm):
    """
    Form for updating inventory information.

    Meta:
        model (Inventory): The Inventory
        model associated with the form.
        fields (list): The fields to include
        in the form.
        widgets (dict): Custom widgets for
        form fields.
        labels (dict): Custom labels for form fields.

    Methods:
        clean(): Validates form data and adds custom error messages if needed.

    """
    class Meta:
        model = Inventory
        fields = ['quantity_in_stock', 'quantity_allocated']
        widgets = {
            'quantity_in_stock': forms.NumberInput(attrs={'class':
                'form-control'}),
            'quantity_allocated': forms.NumberInput(attrs={'class':
                'form-control'}),
        }
        labels = {
            'quantity_in_stock': 'Quantity in Stock',
            'quantity_allocated': 'Quantity Allocated',
        }

    def clean(self):
        cleaned_data = super().clean()
        quantity_in_stock = cleaned_data.get('quantity_in_stock')
        quantity_allocated = cleaned_data.get('quantity_allocated')

        if quantity_in_stock < 0:
            self.add_error('quantity_in_stock',
                           'Quantity in stock cannot be negative.')

        if quantity_allocated < 0:
            self.add_error('quantity_allocated',
                           'Quantity allocated cannot be negative.')

class FeedbackForm(forms.ModelForm):
    """
    Form for submitting feedback.

    Meta:
        model (Feedback): The Feedback model associated with the form.
        fields (list): The fields to include in the form.
        widgets (dict): Custom widgets for form fields.

    """
    class Meta:
        model = Feedback
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 4,
                                             'placeholder':
                                                 'Enter your feedback here'}),
        }         

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Product, Category, Inventory
from checkout.models import Order, OrderLineItem
from profiles.models import UserProfile
from .forms import QuantityForm, ProductForm, InventoryForm, FeedbackForm, Feedback
from django.http import JsonResponse, HttpResponseBadRequest
from django.urls import reverse


import logging


def all_products(request):
    """
    View function for displaying all products, with optional filtering and sorting.
    """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None

    if request.GET:
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter a search term to find products.")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)
            if products.count() == 0:
                messages.error(request,
                               "No products found matching your criteria.")

        # Sorting logic
        if 'sort' in request.GET:
            sort = request.GET['sort']
            if sort == 'price_asc':
                products = products.order_by('price')
            elif sort == 'price_desc':
                products = products.order_by('-price')
            elif sort == 'name_az':
                products = products.order_by('name')
            elif sort == 'name_za':
                products = products.order_by('-name')

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
    }

    return render(request,
                  'products/products.html', context)


def product_detail(request, product_id):
    """
    View function for displaying the details of a specific product, including its
    description, inventory, feedback, and options to add it to the shopping bag.
    """

    product = get_object_or_404(Product, pk=product_id)
    bag = request.session.get('bag', {})
    inventory = Inventory.objects.filter(product=product).first()
    if not inventory:
        inventory = Inventory(product=product,
                              quantity_in_stock=0, quantity_allocated=0)

    has_purchased = False
    if request.user.is_authenticated:
        has_purchased = user_has_purchased(request.user, product)

    feedback_form = FeedbackForm()
    feedbacks = Feedback.objects.filter(product=product)

    if request.method == 'POST':
        form = QuantityForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            bag[product_id] = bag.get(product_id, 0) + quantity
            request.session['bag'] = bag
            messages.success(request, f"{quantity} of {product.name} added to your bag.")
            return redirect(request.POST.get('redirect_url',
                                             reverse('products')))
        else:
            messages.error(request, "There was an error with your form. Please check your input.")
            context = {'product': product, 'form': form}
            return render(request, 'product_detail.html',
                          context)
    else:
        form = QuantityForm(initial={'quantity': 1})

    context = {
        'product': product,
        'inventory': inventory,
        'form': form,
        'is_in_bag': str(product_id) in bag,
        'feedback_form': feedback_form,
        'user_has_purchased': has_purchased,
        'feedbacks': feedbacks,
    }

    return render(request, 'products/product_detail.html',
                  context)


def remove_from_bag(request, item_id):
    """
    View function for removing a product from the shopping bag.
    """

    if request.method == 'POST':
        bag = request.session.get('bag', {})
        product_id = request.POST.get('product_id', None)
        origin = request.POST.get('origin', 'product_detail')

        if product_id and product_id in bag:
            bag.pop(product_id)
            request.session['bag'] = bag

            messages.success(request, "Product removed from your bag successfully.")

            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'status': 'success', 'message': 'Item removed'})

            if origin == 'bag':
                redirect_url = reverse('view_bag')
            else:
                redirect_url = reverse('product_detail', kwargs={'product_id': product_id})

            return redirect(redirect_url)
        else:
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'status': 'error', 'message': 'Item not in bag'})

            messages.error(request, "The item wasn't in your bag.")

            if origin == 'bag':
                redirect_url = reverse('view_bag')
            else:
                redirect_url = reverse('product_detail',
                                       kwargs={'product_id': product_id})

            return redirect(redirect_url)

    return HttpResponseBadRequest("Invalid request. Only POST requests are allowed on this endpoint.")


@login_required
def add_product(request):
    """
    View function for adding a new product to the store.
    """

    if not request.user.is_superuser:
        messages.error(request,
                       'Sorry, you are not allowed to access this page.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, f'Added product: {product.name}')
            return redirect('product_detail', product_id=product.id)
        else:
            messages.error(request,
                           'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
        'is_adding_product': True,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    View function for editing an existing product in the store.
    """

    if not request.user.is_superuser:
        messages.error(request,
                       'Sorry, you are not allowed to access this page.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST,
                           request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request,
                             'Successfully updated product!')
            return redirect(reverse('product_detail',
                                    args=[product.id]))
        else:
            messages.error(request,
                           'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request,
                      f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'is_editing_product': True,
        'product': product,

    }

    return render(request,
                  template, context)


@login_required
def delete_product(request, product_id):
    """
    View function for deleting an existing product from the store.
    """

    if not request.user.is_superuser:
        messages.error(request,
                       'Sorry, you are not allowed to access this page.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product,
                                pk=product_id)

    if request.method == 'POST':
        product.delete()
        messages.success(request, 'Product successfully deleted!')
        return redirect(reverse('products'))

    template = 'products/delete_product.html'
    context = {
        'product': product,
    }

    return render(request, template, context)


@login_required
def update_inventory(request,
                     product_id):
    """
    View function for updating the inventory of a product in the store.
    """

    if not request.user.is_superuser:
        messages.error(request, 'Only store managers can update inventory.')
        return redirect('product_detail',
                        product_id=product_id)

    product = get_object_or_404(Product,
                                pk=product_id)
    inventory, created = Inventory.objects.get_or_create(product=product)

    if request.method == 'POST':
        form = InventoryForm(request.POST, instance=inventory)
        if form.is_valid():
            form.save()
            messages.success(request, 'Inventory updated successfully.')
            return redirect('product_detail',
                            product_id=product_id)
        else:
            messages.error(request,
                           'Failed to update inventory. Please check the form.')
    else:
        form = InventoryForm(instance=inventory)

    context = {
        'form': form,
        'product': product
    }

    return render(request, 'products/update_inventory.html', context)


@login_required
def product_feedback(request, product_id):
    """
    View function for allowing users to submit feedback for a product.
    """
    product = get_object_or_404(Product, pk=product_id)

products/templates/products/add_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Add new Product</title>

</head>

{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="management-wrapper">
                <h2 class="logo-font text-center mb-4">Product Management</h2>
                <h5 class="text-muted text-center">Add a Product</h5>
                <hr>

                <div class="product-form mt-4">
                    <form method="POST" action="{% url 'add_product' %}" class="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name != 'image' %}
                                {{ field | as_crispy_field }}
                             {% else %}
                                {{ field }}
                            {% endif %}
                        {% endfor %}
                        <div class="form-actions text-center mt-3">
                            <a class="btn btn-outline-secondary btn-block btn-danger text-white" href="{% url 'products' %}">Cancel</a>
                            <button class="btn btn-primary btn-block" type="submit">Add New Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>            
    </div>
</div>
{% endblock %}



</body>

</html>

products/templates/products/delete_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Delete Product</title>

</head>
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="management-wrapper">
                <h2 class="logo-font text-center mb-4">Delete Product</h2>
                <hr>
                <p class="text-center">Are you sure you want to delete the product "{{ product.name }}"?</p>
                
                <div class="text-center mt-4">
                    <form method="POST" action="{% url 'delete_product' product.id %}">
                        {% csrf_token %}
                        <a class="btn btn-outline-secondary mr-2" href="{% url 'product_detail' product.id %}">No, take me back</a>
                        <button type="submit" class="btn btn-danger">Yes, delete it</button>
                    </form>
                </div>
            </div>
        </div>            
    </div>
</div>
{% endblock %}
</body>

</html>

products/templates/products/edit_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Edit Product</title>

</head>

{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="management-wrapper">
                <h2 class="logo-font text-center mb-4">Product Management</h2>
                <h5 class="text-muted text-center">Edit a Product</h5>
                <hr>

                <div class="product-form mt-4">
                    <form method="POST" action="{% url 'edit_product' product.id %}" class="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name != 'image' %}
                                {{ field | as_crispy_field }}
                             {% else %}
                                {{ field }}
                            {% endif %}
                        {% endfor %}
                        <div class="form-actions text-center mt-3">
                            <a class="btn btn-outline-secondary btn-block btn-danger text-white" href="{% url 'products' %}">Cancel</a>
                            <button class="btn btn-primary btn-block" type="submit">Updated the Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>            
    </div>
</div>
{% endblock %}
</body>

</html>

products/templates/products/product_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="handmade soap, natural products, vegan products, eco-friendly, organic">
    <title>Product Details</title>
</head>

{% extends "base.html" %}
{% load static %}

{% include 'includes/navbar.html' %}
{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row detail-row mb-4">
        <!-- Product Image Section -->
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2 mt-3 product-detail-container">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid product-image-dt" src="{{ product.image.url }}"
                        alt="{{ product.name }}">
                </a>
                {% else %}
                <img class="card-img-top img-fluid product-image-dt" src="{{ MEDIA_URL }}noimage.png"
                    alt="{{ product.name }}">
                {% endif %}
            </div>
        </div>

        <!-- Product Details Section -->
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details">
                <h2>{{ product.name }}</h2>
                <p><strong>Description:</strong> {{ product.description }}</p>
                <p><strong>Price:</strong> €{{ product.price }}</p>
                {% if product.category %}
                <p><strong>Category:</strong> {{ product.category.name }}</p>
                {% endif %}
                {% if request.user.is_superuser %}
                <div class="superuser-controls">
                    <a href="{% url 'edit_product' product.id %}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{% url 'delete_product' product.id %}" class="btn btn-danger btn-sm"
                        onclick="return confirm('Are you sure you want to delete this product?');">Delete</a>
                </div>
                {% endif %}



                <!-- Inventory Status -->
                <p id="inventoryStatus">
                    <strong>Availability:</strong>
                    {% if product.inventory.quantity_in_stock > 0 %}
                    <span class="text-success"> in stock</span>
                    {% else %}
                    <span class="text-danger p-2"></span>
                    {% endif %}
                </p>
                {% if request.user.is_superuser %}
                <div class="mt-3 mb-2">
                    <a href="{% url 'products:update_inventory' product.id %}" class="btn btn-warning">Update
                        Inventory</a>
                </div>
                {% endif %}

            </div>

            <!-- Add to Bag Form -->
            {% if product.inventory.quantity_in_stock > 0 %}
            <form action="{% url 'add_to_bag' product.id %}" method="post" class="product-form mt-3">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-12">
                        <p><strong>Quantity:</strong></p>
                        <div class="form-group w-50">
                            <div class="input-group">
                                {{ form.quantity }}
                                {% if form.quantity.errors %}
                                <div class="error-q">{{ form.quantity.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <!-- Action Buttons -->
                    <div class="col-12 button-container">
                        <a href="{% url 'products' %}" class="btn btn-custom-back btn-custom">
                            <i class="fas fa-chevron-left"></i> Keep Shopping
                        </a>
                        <input type="submit" class="btn btn-custom-add btn-custom text-uppercase" value="Add to Bag">
                    </div>
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                </div>
            </form>
            {% else %}
            <button class="btn btn-danger btn-custom" disabled>Out of Stock</button>
            {% endif %}

            <!-- Remove from Bag Form -->
            {% if is_in_bag %}
            <div class="button-container">
                <form id="removeItemForm" action="{% url 'remove_from_bag' product.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <input type="hidden" name="origin" value="product_detail">
                    <button type="submit" class="btn btn-warning btn-custom">Remove from Bag</button>
                </form>
            </div>

            {% endif %}
            <!-- Feedback Section -->
            {% if user_has_purchased %}
            <form method="post" action="{% url 'product_feedback' product.id %}">
                {% csrf_token %}
                {{ feedback_form|crispy }}
                <button type="submit" class="btn btn-primary mt-2">Submit Feedback</button>
            </form>
            {% endif %}

            <!-- Feedback Section -->
            <div class="product-feedbacks container my-4">
                <hr>
                <h3 class="logo-font text-center mb-4">Customer Feedback</h3>
                <hr>

                {% if feedbacks %}
                <div class="feedback-list">
                    {% for feedback in feedbacks %}
                    <div class="feedback mb-3 p-3 border rounded  bg-highlight">
                        <div class="feedback-header p-2 d-flex justify-content-between text-highlight">
                            <strong class="feedback-user">{{ feedback.user.username }}</strong>
                            <span class="feedback-date">{{ feedback.created_at|date:"d/m/Y H:i" }}</span>
                        </div>
                        <p class="feedback-comment mt-2">{{ feedback.comment }}</p>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <p class="text-center">No feedback has been provided for this product yet.</p>
                {% endif %}
            </div>

        </div>
    </div>
</div>

{% endblock %}

<script>
    document.getElementById('removeItemForm').onsubmit = function (event) {
        event.preventDefault();
        removeFromBag();
    };

    function removeFromBag() {
        var productId = document.querySelector('#removeItemForm [name="product_id"]').value;
        var csrfToken = document.querySelector('#removeItemForm [name="csrfmiddlewaretoken"]').value;
        var xhr = new XMLHttpRequest();
        xhr.open('POST', `{% url 'remove_from_bag' product.id %}`, true);
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.setRequestHeader('X-CSRFToken', csrfToken);
        xhr.onload = function () {
            if (xhr.status == 200) {
                alert('Item removed successfully!');
                location.reload();
            } else {
                alert('An error occurred.');
            }
        };
        xhr.send('product_id=' + productId);
    }
</script>
</body>

</html>

products/templates/products/products.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Products</title>

</head>

{% extends "base.html" %}
{% load static %}

{% include 'includes/navbar.html' %}

{% block content %}
<div class="overlay"></div>
<div class="container bg-products py-4">
    <h2 class="text-center mt-5 mb-4">Explore Our Unique Soap Collection</h2>

    <!-- Sorting Dropdown -->
    <div class="sorting-dropdown mb-4">
        <select id="sort-by" onchange="sortProducts()" class="form-control">
            <option value="">Sort by</option>
            <option value="price_asc">Price (Low to High)</option>
            <option value="price_desc">Price (High to Low)</option>
            <option value="name_az">Name (A to Z)</option>
            <option value="name_za">Name (Z to A)</option>
        </select>
    </div>

    <!-- Loop for sorting products and display in the sections -->
    <div class="row">
        {% for product in products %}
        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card product-card h-100 shadow-sm">
                {% if product.image %}
                <a href="{% url 'product_detail' product.id %}">
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }} - Handmade Natural Soap">
                </a>
                {% else %}
                <a href="{% url 'product_detail' product.id %}">
                    <img src="{{ MEDIA_URL }}noimage.png" class="card-img-top" alt="No image available">
                </a>
                {% endif %}

                <!-- Display layout of products cards -->
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description|truncatewords:20 }}</p>
                    <div class="buy-info d-flex justify-content-between align-items-center mt-3">
                        <span class="price-highlight">€{{ product.price }}</span>

                        <!-- Add to Bag Form -->
                        <form action="{% url 'add_to_bag' product.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="redirect_url" value="{% url 'products' %}">
                            <button type="submit" class="btn btn-success"
                                {% if not product.inventory.quantity_in_stock %} disabled {% endif %}>Add to
                                bag</button>
                        </form>
                    </div>
                </div>
                <div class="card-footer bg-white border-0">
                    {% if product.rating %}
                    <div class="product-rating">
                        <span class="rating">{{ product.rating }}</span>
                        <i class="fas fa-star rated"></i>
                    </div>
                    {% else %}
                    <small class="text-muted">
                        {% if not product.inventory.quantity_in_stock %}
                        <div class="out-of-stock-info text-danger">
                            Out of Stock
                        </div>
                        {% endif %}
                    </small>
                    {% endif %}
                </div>

                <!-- Superuser Edit/Delete Buttons -->
                {% if request.user.is_superuser %}
                <div class="card-footer bg-white text-right">
                    <a href="{% url 'edit_product' product.id %}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{% url 'delete_product' product.id %}" class="btn btn-danger btn-sm">Delete</a>
                </div>
                {% endif %}

            </div>
        </div>
        {% empty %}
        <div class="col-12">
            <p class="text-center">Our soap artisans are working on new creations. Check back soon!</p>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    function sortProducts() {
        var sortingMethod = document.getElementById('sort-by').value;
        var currentUrl = window.location.href;
        var newUrl = new URL(currentUrl);
        newUrl.searchParams.set('sort', sortingMethod);
        window.location.href = newUrl;
    }
</script>

{% endblock %}

</body>

</html>